"use client"

import { Inter } from 'next/font/google'
import { randomNumberHelper } from "@/helpers/helpers";
import { Steam } from "@/components/animation/animation";
import './globals.scss'
import styles from "./styles.module.scss";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ['latin'] })

type AnimationConfig = {
  steamsDelays: number[]
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const STEAM_DELAY_MIN = 40;
  const STEAM_DELAY_MAX = 50;

  const [animationConfig, setAnimationConfig] = useState<AnimationConfig>({
    steamsDelays: [],
  })

  useEffect(() => {
    const viewPortWidth: number = window.visualViewport?.width!;
    const steamBlockWidth: number = viewPortWidth * 0.05;
    const quantityOfSteamBlocks = Math.ceil(viewPortWidth / steamBlockWidth);
    setAnimationConfig({
      steamsDelays: Array.from(Array(quantityOfSteamBlocks).keys())
    })
  }, [])
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <div className={styles.steamSource}>
        {animationConfig.steamsDelays.map((_, index) => (
          <Steam
            key={index}
            delayValue={
              randomNumberHelper(1, animationConfig.steamsDelays.length) +
              randomNumberHelper(STEAM_DELAY_MIN, STEAM_DELAY_MAX)
            }
          />
        ))}
      </div>
      </body>
    </html>
  )
}
